[[main]]
name = "Trang chủ"
url = "/vi/"
weight = 1

[[main]]
name = "Reel"
pageRef = "reel"
weight = 2

[[main]]
name = "Tín chỉ"
pageRef = "credits"
weight = 3

[[main]]
name = "Portfolio âm thanh"
pageRef = "portfolio"
weight = 4

[[main]]
name = "Dự án cá nhân"
pageRef = "projects"
weight = 5

[[main]]
name = "Blog"
pageRef = "blog"
weight = 6

[[main]]
name = "Giới thiệu"
pageRef = "bio"
weight = 7

[[main]]
name = "Liên hệ"
pageRef = "contact"
weight = 8
