import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import{BrowserRouter,Link,Navigate,Route,Routes,useNavigate,useParams}from"react-router-dom";
import{onAuthStateChanged,signInWithEmailAndPassword,signOut,User}from"firebase/auth";
import{auth}from"./firebase";
import{emptyEntry,Entry,EntryType,getEntry,listEntries,removeEntry,requestPublish,saveEntry}from"./content";
import"./styles.css";
function App(){const[user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[owner,setOwner]=useState(false);useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);setOwner(Boolean(u&&(await u.getIdTokenResult(true)).claims.admin===true));setReady(true)}),[]);if(!ready)return <p>Loading…</p>;return <Routes><Route path="/login" element={!owner?<Login/>:<Navigate to="/entries"/>}/><Route path="*" element={owner?<Shell user={user!}/>:user?<main><p>Access denied. This account is not the site owner.</p><button onClick={()=>signOut(auth)}>Sign out</button></main>:<Navigate to="/login"/>}/></Routes>}
function Login(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");return <main className="login"><h1>Portfolio editor</h1><form onSubmit={async e=>{e.preventDefault();setError("");try{await signInWithEmailAndPassword(auth,email,password)}catch(err){setError((err as Error).message)}}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>Sign in</button>{error&&<p role="alert">{error}</p>}</form></main>}
function Shell({user}:{user:User}){return <main><header><h1>Portfolio editor</h1><span>{user.email}</span><button onClick={()=>signOut(auth)}>Sign out</button></header><Routes><Route path="/" element={<Navigate to="/entries"/>}/><Route path="/entries" element={<Listing/>}/><Route path="/entries/new" element={<Editor/>}/><Route path="/entries/:id" element={<Editor/>}/></Routes></main>}
function Listing(){const[items,setItems]=useState<Entry[]>([]),[type,setType]=useState(""),[status,setStatus]=useState("");useEffect(()=>{listEntries(type,status).then(setItems).catch(e=>alert(e.message))},[type,status]);return <><nav><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{["blog","portfolio","project","credit"].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All states</option><option>draft</option><option>published</option></select><Link className="button" to="/entries/new">New entry</Link></nav><ul className="entries">{items.map(item=><li key={item.id}><Link to={`/entries/${item.id}`}><strong>{item.en.title||item.slug}</strong><span>{item.type} · {item.status}</span></Link></li>)}</ul></>}
function Editor(){const{id}=useParams(),navigate=useNavigate(),[entry,setEntry]=useState<Entry>(emptyEntry()),[message,setMessage]=useState("");useEffect(()=>{if(id)getEntry(id).then(setEntry).catch(e=>setMessage(e.message))},[id]);const update=(key:keyof Entry,value:unknown)=>setEntry(old=>({...old,[key]:value}));const localized=(lang:"en"|"vi",key:"title"|"summary"|"body",value:string)=>setEntry(old=>({...old,[lang]:{...old[lang],[key]:value}}));async function save(){try{await saveEntry(entry);setMessage("Saved");if(!id)navigate("/entries")}catch(e){setMessage((e as Error).message)}}return <section><nav><Link to="/entries">← Entries</Link><span>{message}</span></nav><div className="grid"><label>Type<select value={entry.type} onChange={e=>update("type",e.target.value as EntryType)}>{["blog","portfolio","project","credit"].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<span>{entry.status}</span></label><label>Slug<input value={entry.slug} onChange={e=>update("slug",e.target.value)}/></label><label>Year<input type="number" value={entry.year||""} onChange={e=>update("year",Number(e.target.value))}/></label><label>Role<input value={entry.role||""} onChange={e=>update("role",e.target.value)}/></label><label>Category<input value={entry.category||""} onChange={e=>update("category",e.target.value)}/></label></div>{(["en","vi"] as const).map(lang=><fieldset key={lang}><legend>{lang.toUpperCase()}</legend><label>Title<input value={entry[lang].title} onChange={e=>localized(lang,"title",e.target.value)}/></label><label>Summary<input value={entry[lang].summary} onChange={e=>localized(lang,"summary",e.target.value)}/></label><label>Markdown body<textarea rows={10} value={entry[lang].body} onChange={e=>localized(lang,"body",e.target.value)}/></label><article className="preview"><h3>{entry[lang].title||"Preview"}</h3><p>{entry[lang].body}</p></article></fieldset>)}<div className="grid"><label>YouTube URL<input value={entry.youtubeUrl||""} onChange={e=>update("youtubeUrl",e.target.value)}/></label><label>SoundCloud URL<input value={entry.soundcloudUrl||""} onChange={e=>update("soundcloudUrl",e.target.value)}/></label><label>Tags (comma-separated)<input value={(entry.tags||[]).join(", ")} onChange={e=>update("tags",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/></label></div><footer><button onClick={save}>Save draft</button>{id&&<><button disabled title="Publish automation is not configured yet" onClick={async()=>{try{await requestPublish(id,entry.status==="published"?"unpublish":"publish")}catch(e){setMessage((e as Error).message)}}}>{entry.status==="published"?"Unpublish":"Publish"} (unavailable)</button><button className="danger" onClick={async()=>{if(confirm("Delete this entry?")){await removeEntry(id);navigate("/entries")}}}>Delete</button></>}</footer><p>Publishing is unavailable until the secure GitHub build integration is configured.</p></section>}
createRoot(document.getElementById("root")!).render(<BrowserRouter basename="/admin"><App/></BrowserRouter>);
